fails:Thread.handle_interrupt with :on_blocking defers interrupts until the next blocking call
